MODEL:
  TYPE: distillation
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 270000
  STEPS: [0, 180000, 240000]
  WARM_UP_ITERS: 1000
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
RESNETS:
  CHANNEL_RATIO: 1.0
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('coco_2017_train',)
  SCALES: (600,)
  MAX_SIZE: 1000
  RPN_STRADDLE_THRESH: -1  # default 0
  AUTO_RESUME: True
TEST:
  DATASETS: ('coco_2017_val',)
  SCALES: (600,)
  MAX_SIZE: 1000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
DISTILLATION:
  DISTILLATION_ON: True
  LOSS_ALPHA: 0.5
  LOSS_GAMMA: 2.0
  IGNORED_LABEL: -1
  ADAPTIVE_NORMALIZER: True
  LOGITS_POWER: 1.8
  TEMPERATURE: 1.0
  UNLABEL_DISTILLATION: True
  UNLABEL_DATASETS: ('coco_2017_train','coco_2017_unlabel_R101_600')
  